### PR TITLE
Fetch hammer-time from npm instead of bower

### PR DESCRIPTION
**Pull request by john-griffin**
Now that ember-cli no longer includes bower by default it makes sense to move the hammer-time dependancy to npm. Tested out on a real app.

### CODE REVIEW

**Comment by eriktrom** [comment]
This LGTM

@runspired - any concerns?

**Comment by runspired** [comment]
LGTM

**Comment by john-griffin** [comment]
Thanks. Seems to be an issue with the ember-try config causing the build to fail, this branch is passing on 1.13 locally.

**Comment by rwwagner90** [comment]
I'd recommend using https://github.com/dfreeman/ember-cli-node-assets to accomplish this, but this approach does also work, AFAIK

**Comment by eriktrom** [comment]
@john-griffin - thanks a bunch for the pr
@rwwagner90 - agree thats a good addon, but perhaps better for apps. Feel free to make a pr though if u want

@runspired - merging, publish to npm at will (dont have access for this one LOL )

**Comment by runspired** [comment]
@eriktrom I will add you later when I get a moment to clone locally

**Pull request merged**
