### PR TITLE
Update Ember and fix AST issues

### LINKED ISSUE #38: Breaks the build in 2.15-beta.1
If I add this addon to a new 2.15-beta.1 app, I'm getting build errors like these:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (preprocessedApp & templates)] failed with:
TypeError: Cannot read property 'visitors' of undefined
    at preprocess (P:\Projects\reproduction-build1\node_modules\ember-source\dist\ember-template-compiler.js:3921:47)
    at exports.precompile (P:\Projects\reproduction-build1\node_modules\ember-source\dist\ember-template-compiler.js:1551:42)
    at Object.exports.default (P:\Projects\reproduction-build1\node_modules\ember-source\dist\ember-template-compiler.js:16409:12)
    at Object.template (P:\Projects\reproduction-build1\node_modules\ember-cli-htmlbars\utils.js:29:40)
    at TemplateCompiler.processString (P:\Projects\reproduction-build1\node_modules\ember-cli-htmlbars\index.js:76:40)
    at Promise.then.result.output (P:\Projects\reproduction-build1\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23)
    at initializePromise (P:\Projects\reproduction-build1\node_modules\rsvp\dist\rsvp.js:567:5)
    at new Promise (P:\Projects\reproduction-build1\node_modules\rsvp\dist\rsvp.js:1039:33)
    at P:\Projects\reproduction-build1\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:40:18
    at tryCatch (P:\Projects\reproduction-build1\node_modules\rsvp\dist\rsvp.js:525:12)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (P:\Projects\reproduction-build1\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (P:\Projects\reproduction-build1\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (P:\Projects\reproduction-build1\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:10:53)
    at mergeTrees (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\merge-trees.js:85:33)
    at EmberApp._mergeTrees (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\ember-app.js:1840:12)
    at EmberApp.appAndDependencies (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\ember-app.js:1130:51)
    at EmberApp.javascript (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\ember-app.js:1253:30)
    at EmberApp.toArray (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\ember-app.js:1697:12)
    at EmberApp.toTree (P:\Projects\reproduction-build1\node_modules\ember-cli\lib\broccoli\ember-app.js:1719:38)
    at module.exports (P:\Projects\reproduction-build1\ember-cli-build.js:28:14)
```

* * *

Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 2.15.0-beta.1
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: win32 x64
npm: 4.6.1
yarn: 0.27.5

ember-cli-babel: 6.6.0
ember-cli-htmlbars: 2.0.2
```

### PR DESCRIPTION
**Pull request by rwwagner90**
This should fix #38

### CODE REVIEW

**Comment by rwwagner90** [comment]
@runspired @eriktrom @kybishop something was broken with `.bind`, so I had to store config values myself. There is probably a better way to do this, if either of you know of something. We could also use something like https://github.com/null-null-null/ember-get-config to grab the config values instead. Please let me know your thoughts and preference 😄

**Comment by eriktrom** [comment]
This is fine by me - I'm curious though - the code, besides the updates, and the refactors, has the same logic.

Except the bind - is it possible that upstream there is a bug with ember-cli where `setupPreprocessorRegistry` is being called twice, where registry.add is borking things up?

I read through the code, and based on your comment and my close reading, I still don't get what exactly broke, and why?

at any rate, if it solves the problem LGTM

**Comment by rwwagner90** [comment]
@eriktrom I searched all of GitHub for `htmlbars-ast-plugin` and was unable to find anyone else passing a config in. I believe whatever scope it binds to by default was messed up by the bind and caused it to have the incorrect context when doing whatever it was doing with `visitors`. I would love to more fully understand what broke, but I have no idea where to find the relevant code in Ember itself or how to begin tracking it down.

**Comment by eriktrom** [comment]
thanks @rwwagner90 for the update - i may have searched around too had u not mentioned u tried

in the end, I like the way its written better now, nice work - could argue that `.bind(Ctor, config)` was a bit too magical for most anyway

**Comment by rwwagner90** [comment]
@eriktrom I will go ahead and merge then, and if @runspired or @kybishop have any better ideas, we can always change it later.

**Pull request merged**
