### PR TITLE
Fix for upcoming FastBoot 1.0 breaking changes

### PR DESCRIPTION
**Pull request by simonihmig**
`process.env.EMBER_CLI_FASTBOOT` will be gone in FastBoot 1.0. This should now work in pre and post 1.0 versions of `ember-cli-fastboot`. See https://github.com/ember-fastboot/ember-cli-fastboot/issues/360 for context.

Also includes some ES6 code style cleanup...

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hi @simonihmig I'm confused, how does fastboot know to ignore importing it now?

**Comment by simonihmig** [comment]
It does not. That's why there is this guard now to not run browser stuff in FastBoot: https://github.com/html-next/ember-hammertime/pull/34/files#diff-168726dbe96b3ce427e7fedce31bb0bcR32

For FastBoot 1.0 there will be just one build, not two separate like now (browser + FastBoot). So all browser JS will also be part of the FastBoot app, so we have to use guards. Here is some more context: https://gist.github.com/kratiahuja/fd073007e10abb9db0a2ec42bc1d7c17

I guess there will be some official blog post some time soon explaining the future changes, but I wanted to prepare things in advance, at least for those addons I need in my FastBoot app...

**Comment by rwwagner90** [comment]
@simonihmig I just hit these issues myself, so I am going to merge this. After looking at the changes, it appears this is only compatible with the new fastboot standards right? Isn't there something else we need to do to make sure it works with both the old beta standards and the new rc standards?

**Comment by simonihmig** [comment]
@rwwagner90 Thanks for merging. I actually see no reason why this should not work with the older beta versions of FastBoot as well!

**Pull request merged**
